name: Sync upstream master and main

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    if: github.ref == 'refs/heads/automation'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout automation branch
        uses: actions/checkout@v4
        with:
          ref: automation
          fetch-depth: 0

      - name: Configure git and add upstream
        run: |
          git remote add upstream https://github.com/bitcoinops/bitcoinops.github.io.git
          git fetch upstream master
          git config user.email "action@github.com"
          git config user.name "GitHub Action"

      - name: Sync and push master branch
        run: |
          git checkout --track origin/master
          git reset --hard upstream/master
          git push origin master

      - name: Sync and push main branch
        run: |
          git checkout --track origin/main
          git reset --hard upstream/master
          git push origin main
